platform :ios, '8.0'

target 'OTScreenShareAccPackKit' do
    pod 'OTAcceleratorPackUtil', '~> 2.0.0-beta'
end

target 'OTScreenShareKit' do
    pod 'OTAcceleratorPackUtil', '~> 2.0.0-beta'
end

target 'OTScreenShareKitStatic' do
    pod 'OTAcceleratorPackUtil', '~> 2.0.0-beta'
end

target 'OTScreenShareKitTests' do
    pod 'Kiwi'
end
